import type { Metadata } from "next";
import { Inter as FontSans } from 'next/font/google';
import { cn } from "@/lib/utils";
import "./globals.css";
import { Navbar } from "@/components/ui/navbar";

const fontSans = FontSans({
  variable: "--font-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" suppressHydrationWarning>
      <body
        className={cn(
          "min-h-screen font-sans antialiased",
          fontSans.variable
        )}
        suppressHydrationWarning
      >
          {/* Navbar de navegación principal 
          <Navbar />
          <div style={{ paddingTop: '64px' }}>
          </div>*/}
          {children}

      </body>
    </html>
  );
}
